version: '3.5'
volumes:
  files:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local
  redis:
    driver: local

services:
  owncloud:
    container_name: owncloud
    image: owncloud/server:10.11
    restart: unless-stopped
    ports:
      - 180.1.1.100:80:8080
    depends_on:
      - db
      - redis
    environment:
      - APACHE_DOCUMENT_ROOT="/var/www/owncloud"
      - APACHE_SERVER_NAME="dropbox.com"
      - OWNCLOUD_TRUSTED_DOMAINS=180.1.1.100,dropbox.com,www.dropbox.com
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=toor
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - OWNCLOUD_DOMAIN=dropbox.com
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    volumes:
      - files:/mnt/data
  db:
    container_name: owncloud_db
    image: webhippie/mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=owncloud
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud
      - MARIADB_DATABASE=owncloud
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup

  redis:
    container_name: owncloud_redis
    image: webhippie/redis:latest
    restart: unless-stopped
    environment:
      - REDIS_DATABASES=1
    volumes:
      - redis:/var/lib/redis
  nginx:
    container_name: nginx_owncloud
    image: nginx
    restart: unless-stopped
    volumes: 
      - /root/owncloud/SSL:/SSL
      - /root/owncloud/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 180.1.1.100:443:443
