version: "3.9"

services:
  ntp:
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      - 180.1.1.140:123:123/udp
    environment:
      - NTP_SERVERS=172.30.0.2
      - NOCLIENTLOG=true
